In [19]:
import numpy as np
import random

# Defining the states and actions
states = [0,1, 2, 3, 4, 5]
actions = [0, 1, 2, 3, 4, 5]

# Defining the rewards
rewards = np.array([[-1, -1, -1, -1, 0, -1],
                [-1, -1, -1, 0, -1, 100],
                [-1, -1, -1, 0, -1, -1],
                [-1, 0, 0, -1, 0, -1],
                [0, -1, -1, 0, -1, 100],
                [-1, 0, -1, -1, 0, 100]])


# Define the Q-table
q_table = np.zeros((len(states), len(actions)),dtype=int)

print("Reward table:")
print(rewards)
print()
print("Initial Q-Table:")
print(q_table)

Reward table:
[[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [  0  -1  -1   0  -1 100]
 [ -1   0  -1  -1   0 100]]

Initial Q-Table:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [21]:
alpha = 0.1
gamma = 0.9
epsilon = 0.1

In [25]:
def q_learning(state, q_table, rewards, alpha, gamma):
    action = np.argmax(q_table[state, :])
    next_state = action
    reward = rewards[state, action]
    q_table[state, action] = q_table[state, action] + int(alpha * (reward + gamma * np.max(q_table[next_state, :]) - q_table[state, action]))
    return next_state, q_table

# Run the Q-Learning algorithm for 50 episodes
for episode in range(50):
    state = np.random.choice(states)
    while state != 5:
        state, q_table = q_learning(state, q_table, rewards, alpha, gamma)
    print(f"Q-Table after episode {episode + 1}:")
    print(q_table)

Q-Table after episode 1:
[[ 5 75  0  0  0  0]
 [ 7  0  0  0  1 97]
 [23  0  0  3  0  0]
 [ 5 48  0  0  0  0]
 [25  0  0  0  0  0]
 [16  0  0  0  0  0]]
Q-Table after episode 2:
[[ 5 76  0  0  0  0]
 [ 7  0  0  0  1 98]
 [27  0  0  3  0  0]
 [ 5 48  0  0  0  0]
 [25  0  0  0  0  0]
 [16  0  0  0  0  0]]
Q-Table after episode 3:
[[ 5 76  0  0  0  0]
 [ 7  0  0  0  1 98]
 [27  0  0  3  0  0]
 [ 5 48  0  0  0  0]
 [25  0  0  0  0  0]
 [16  0  0  0  0  0]]
Q-Table after episode 4:
[[ 5 76  0  0  0  0]
 [ 7  0  0  0  1 98]
 [27  0  0  3  0  0]
 [ 5 48  0  0  0  0]
 [25  0  0  0  0  0]
 [16  0  0  0  0  0]]
Q-Table after episode 5:
[[ 5 77  0  0  0  0]
 [ 7  0  0  0  1 99]
 [27  0  0  3  0  0]
 [ 5 48  0  0  0  0]
 [29  0  0  0  0  0]
 [16  0  0  0  0  0]]
Q-Table after episode 6:
[[  5  78   0   0   0   0]
 [  7   0   0   0   1 100]
 [ 27   0   0   3   0   0]
 [  5  48   0   0   0   0]
 [ 33   0   0   0   0   0]
 [ 16   0   0   0   0   0]]
Q-Table after episode 7:
[[  5  78   0   0   0   0]


In [ ]:
import numpy as np

# Define the states and actions
states = [0, 1, 2, 3, 4, 5]
actions = [0, 1, 2, 3, 4, 5]

# Define the rewards
rewards = np.array([[-1, -1, -1, -1, 0, -1],
                    [-1, -1, -1, 0, -1, 100],
                    [-1, -1, -1, 0, -1, -1],
                    [-1, 0, 0, -1, 0, -1],
                    [0, -1, -1, 0, -1, 100],
                    [-1, 0, -1, -1, 0, 100]])

# Define the Q-table
q_table = np.zeros((len(states), len(actions)), dtype=int)

# Set the learning rate and discount factor
alpha = 0.1
gamma = 0.9

# Run the Q-Learning algorithm for 50 episodes
for episode in range(50):
    # Set the initial state
    state = np.random.choice(states)
    while state != 5:
        # Choose the action with the highest Q-value
        action = np.argmax(q_table[state, :])
        # Update the Q-value for the chosen action
        next_state = action
        reward = rewards[state, action]
        q_table[state, action] = q_table[state, action] + int(alpha * (reward + gamma * np.max(q_table[next_state, :]) - q_table[state, action]))
        state = next_state
    # Print the updated Q-table after each episode
    print(f"Q-Table after episode {episode + 1}:")
    print(q_table)

In [27]:
import numpy as np

class QLearning:
    def __init__(self, env, alpha=0.1, gamma=0.9, epsilon=0.1):
        self.env = env
        self.alpha = alpha
        self.gamma = gamma
        self.epsilon = epsilon

        self.Q = np.zeros((env.observation_space.n, env.action_space.n))

    def epsilon_greedy_policy(self, state):
        if np.random.rand() < self.epsilon:
            action = np.random.choice(env.action_space.n)
        else:
            action = np.argmax(self.Q[state])
        return action

    def learn(self, num_episodes):
        for episode in range(num_episodes):
            print(f"Episode: {episode}")

            # Reset the environment and initialize the episode
            state = env.reset()

            # Run the episode
            done = False
            while not done:
                # Select an action
                action = self.epsilon_greedy_policy(state)

                # Take the action and observe the outcome
                next_state, reward, done, _ = env.step(action)

                # Update the Q-table
                self.Q[state, action] += self.alpha * (reward + self.gamma * np.max(self.Q[next_state]) - self.Q[state, action])

                # Update the state
                state = next_state
           
            # Display Q-table
            print("Q-table:")
            print("---------------------------------")
            for row in self.Q:
                for item in row:
                    print(f"{item:.3f} ", end='')
                print()
            print("---------------------------------")

            # Display R-table
            print("\nR-table:")
            print("---------------------------------")
            for state in env.env.P:
                print(f"State {state}:")
                for action, probabilities in env.env.P[state].items():
                    print(f"    Action {action}:")
                    for next_state, probability, reward, _ in probabilities:
                        print(f"        Next state: {next_state}, Probability: {probability:.3f}, Reward: {reward}")
            print("---------------------------------")

if __name__ == "__main__":
    from gym import make
    env = make("FrozenLake-v1")  # Use FrozenLake-v1 instead of FrozenLake-v0

    agent = QLearning(env)
    agent.learn(100)


Episode: 0


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices